version: '2'

services:

    workspace:
        build:
            context: ./workspace
        volumes_from:
            - volumes_source
        # if you want to start blockchain container automatically
        # links:
        #   - testrpc
        #   - geth
        #   - ganache
        # if you want to connect from host
        # like localhost:3000
        # ports:
        #     - "3000:3000"
        #     - "8080:8080"
        tty: true
        environment:
            TESTRPC_PORT: 8545
            GETH_RPC_PORT: 8545
            GANACHE_RPC_PORT: 8545
        networks:
            - blockchain

    geth:
        build:
            context: ./geth
        volumes_from:
            - volumes_data
        # if you want to connect from host
        # ports:
        #     - "8545:8545"
        #     - "8546:8546"
        #     - "30303:30303"
        #     - "30303/udp:30303/udp"
        # random port
        ports:
            - "8545"
            - "8546"
            - "30303"
            - "30303/udp"
        # stdin_open: true
        # tty: true
        environment:
            GOROOTBASE: /usr/local
            GOROOT: /usr/local/go
            GOPATH: /go
        networks:
            - blockchain

    ganache:
        build:
            context: ./ganache
        volumes_from:
            - volumes_source
        # if you want to connect from host
        # like localhost:8545
        # ports:
        #    - "8545:8545"
        # random port
        ports:
            - "8545"
        networks:
            - blockchain

    volumes_source:
        build: ./volumes/application
        volumes:
            - ./app:/usr/share/app

    volumes_data:
        build: ./volumes/data
        volumes:
            - ./data/geth:/geth
            - ./data/keystore:/keystore

networks:
    blockchain:
        driver: "bridge"
